WebBanSach/Areas/Admin/Controllers/CovertTypeController.cs
using Microsoft.AspNetCore.Mvc;
using WebBanSach.DataAccess.Repository.IRepository;
using WebBanSach.Model;

namespace WebBanSach.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }

        public IActionResult Create()
        {
            return View();
        }

        // post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
           
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["Sucess"] = "CoverType Create Sucessfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }  
            
            var covertTypefromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
          
            if (covertTypefromDbFirst == null)
            {
                return NotFound();
            }

            return View(covertTypefromDbFirst);
        }

        // post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {           
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["Sucess"] = "Cover Type Update Sucessfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coverTypefromDb = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
           
            if (coverTypefromDb == null)
            {
                return NotFound();
            }

            return View(coverTypefromDb);
        }

        // post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
          
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                _unitOfWork.CoverType.Remove(obj);
                _unitOfWork.Save();
                TempData["Sucess"] = "Covert Type Delete Sucessfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }

    }
}

WebBanSach/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebBanSach.DataAccess.Repository.IRepository;
using WebBanSach.Model;
using WebBanSach.Model.ViewModel;

namespace WebBanSach.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Product> objProductTypeList = _unitOfWork.Product.GetAll();
            return View(objProductTypeList);
        }

        public IActionResult Create()
        {
            return View();
        }

        // post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product obj)
        {
           
            if (ModelState.IsValid)
            {
                _unitOfWork.Product.Add(obj);
                _unitOfWork.Save();
                TempData["Sucess"] = "product Create Sucessfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }

        public IActionResult Upsert(int? id)
        {



            ProductVM productVM = new ProductVM();
            productVM.product = new Product(); // Initialize the product property
            productVM.CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            productVM.CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            if (id == null || id == 0)
            {
                // create product
                return View(productVM);
            }
            else
            {
                // update product
                productVM.product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                if (productVM.product == null)
                {
                    return NotFound();
                }
                return View(productVM);
            }
        }


        // post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            var count = Request.Form.Files.Count;
            if (ModelState.IsValid)
            {
                // upload images
                string wwwRootPath = _webHostEnvironment.WebRootPath;
           
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);
                    if (obj.product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.product.ImageUrl = @"images\products\" + fileName + extension;

                }
                if (obj.product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.product);
                }
                else
                {
                    _unitOfWork.Product.Update(obj.product);
                }

                _unitOfWork.Save();
                TempData["Sucess"] = "Product create Sucessfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var ProductfromDb = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
           
            if (ProductfromDb == null)
            {
                return NotFound();
            }

            return View(ProductfromDb);
        }

        // post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
          
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                _unitOfWork.Product.Remove(obj);
                _unitOfWork.Save();
                TempData["Sucess"] = "Covert Type Delete Sucessfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }
        #region Api
        // API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includePr: "Category,CoverType");
            return Json(new { data = productList });
        }
        // post
        [HttpDelete]
        public IActionResult DeletePostApi(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);

            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                if (obj.ImageUrl != null)
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                _unitOfWork.Product.Remove(obj);
                _unitOfWork.Save();

                return Json(new { success = true, message = "Delete Successful" });
            }


            return View(obj);
        }
        #endregion
    }
}

WebBanSach/Areas/Admin/Views/Product/Index.cshtml
@model IEnumerable<Product>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2>Product List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus"></i> Create New Product
            </a>
        </div>
    </div>
    <br /><br />
    <table class="table table-bordered " id="tblData">
        <thead>
        <th>Title</th>
        <th>ISBN</th>
        <th>Author</th>
        <th>Category</th>
        <th></th>
        </thead>

    </table>

</div>
@section Scripts {
    <script src="~/js/product.js"></script>
}

WebBanSach/Areas/Admin/Views/Product/Upsert.cshtml
@using WebBanSach.Model.ViewModel
@model ProductVM


<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>@(Model.product.Id == 0 ? "Create": "Edit") Product</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for=product.Title></label>
            <input asp-for=product.Title class="form-control" />
            <span asp-validation-for=product.Title class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for=product.Description></label>
            <textarea asp-for=product.Description class="form-control">

            </textarea>
            <span asp-validation-for=product.Description class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for=product.ISBN></label>
            <input asp-for=product.ISBN class="form-control" />
            <span asp-validation-for=product.ISBN class="text-danger"></span>
        </div>
       
        <div class="mb-3">
            <label asp-for=product.Author></label>
            <input asp-for=product.Author class="form-control" />
            <span asp-validation-for=product.Author class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for=product.Price50></label>
            <input asp-for=product.Price50 class="form-control" />
            <span asp-validation-for=product.Price50 class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for=product.Price100></label>
            <input asp-for=product.Price100 class="form-control" />
            <span asp-validation-for=product.Price100 class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for=product.ImageUrl></label>
            @* <input type="file" id="ImageUrl" asp-for=product.ImageUrl class="form-control" /> *@
            <input type="file" id="ImageUrl" name="file" asp-for=product.ImageUrl class="form-control" accept="image/*" />
            <span asp-validation-for=product.ImageUrl class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for=product.CategoryId></label>
            <select asp-for="product.CategoryId"
                    asp-items="Model.CategoryList" class="form-control">
                <option value="">-- Select category --</option>
            </select>
            <span asp-validation-for=product.CategoryId class="text-danger"></span>
        </div>
        
        <div class="mb-3">
            <label asp-for=product.CoverTypeId></label>
            <select asp-for="product.CoverTypeId"
                    asp-items="Model.CoverTypeList" class="form-control">
                <option value="">-- Select cover type --</option>
            </select>
            <span asp-validation-for=product.CoverTypeId class="text-danger"></span>
        </div>
      
        @if(Model.product.Id == 0)
        {
            <button type="submit" onclick="return ValidateInput()" class="btn btn-primary">Create</button>
        }
        else
        {
            <button type="submit" class="btn btn-primary">Update</button>
        }
        
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-primary">Back To List</a>
    </div>

</form>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script>
        function ValidateInput() {
            if(document.getElementById("ImageUrl").value == "") {
                          Swal.fire({
                                  icon: "error",
                                  title: "Oops...",
                                  text: "Something went wrong!",
                                  footer: '<a href="#">Why do I have this issue?</a>'
                                });
                                return false;
            }
            return true;
         
        }
    </script>
    <script>
        tinymce.init({
          selector: 'textarea',
          plugins: [
            // Core editing features
            'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'link', 'lists', 'media', 'searchreplace', 'table', 'visualblocks', 'wordcount',
            // Your account includes a free trial of TinyMCE premium features
            // Try the most popular premium features until Aug 26, 2025:
            'checklist', 'mediaembed', 'casechange', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'advtemplate', 'ai', 'uploadcare', 'mentions', 'tinycomments', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown','importword', 'exportword', 'exportpdf'
          ],
          toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography uploadcare | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
          tinycomments_mode: 'embedded',
          tinycomments_author: 'Author name',
          mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
          ],
          ai_request: (request, respondWith) => respondWith.string(() => Promise.reject('See docs to implement AI Assistant')),
          uploadcare_public_key: '354e0aa8be0c329e41d5',
        });
    </script>
}